Question
========
```{r data generation, echo = FALSE, results = "hide", comment=FALSE}
options(OutDec=",")
options(scipen=999)
xmean <-  sample(seq(42, 48, 0.1), 1)
xsd <- round(xmean*0.32, 2)
xsd <- ifelse(xsd*100 == round(xsd, 1)*100, xsd+0.04, xsd)
xprec <- sample(c(1, 2, 2.5), 1)
xconf <- c(sample(c(90, 95, 99), 1))
nok90 <- ceiling(1.64^2 * xsd^2 / xprec^2 )
nok95 <- ceiling(1.96^2 * xsd^2 / xprec^2 )
nok99 <- ceiling(2.58^2 * xsd^2 / xprec^2 )
x1 <- c(nok90, nok95, nok99)
x2 <- c(nok95, nok90, nok99)
x3 <- c(nok99, nok95, nok90)
if (xconf==90) {nok <- c(nok90, nok95, nok99)}
if (xconf==95) {nok <- c(nok95, nok99, nok90)}
if (xconf==99) {nok <- c(nok99, nok90, nok95)}

```
De una población (se asume "infinita" <sup>(1)</sup>) se desea calcular la media de colesterol. Estudios previos muestran que la desviación estándar es de aproximadamente `r xsd` mg/dl. Calcule el tamaño de muestra adecuado para realizar esta estimación con un nivel de confianza del `r xconf`% y una precisión de $\pm$ `r xprec` mg/dl.


<h1 style="font-size:10px;"><sup>(1)</sup>Cuando una población es pequeña, se debe hacer una corrección que se conoce como "corrección por finitud de población", a la fórmula explicada en clase. Pero este concepto se halla más allá de los objetivos de este curso. Por esta razón en el enunciado se escribe "infinita" y se debe aplicar la fórmula explicada en clase.</h1>

¿Cuál de las siguientes respuestas es <font size="5"><span style="color: red;"> **CORRECTA**</span></font>?

Answerlist
----------
* `r nok[1]` 
* `r nok[2]` 
* `r nok[3]` 
* `r nok[2]*2` 
* `r nok[3]*2` 


Solution
========
Para calcular el tamaño de muestra para estimar una media con una confianza determinada, se debe redondear el decimal superior el resultado de la siguiente fórmula:

$\scriptsize \begin{eqnarray}
\text{n} = \dfrac{(z_{(\alpha/2)})^2 * \text{DE}^2}{\text{d}^2}
\end{eqnarray}$

Donde:

* $z_{(\alpha/2)}$ es el valor de la distribución normal (positivo y negativo) que deja en medio el (1-$\alpha$)*100\% de los valores posibles y que corresponde a la confianza con la que se va a realizar la estimación. En el ejercicio, la confianza con la que se quiere realizar la estimación es del `r xconf`% por lo que $z_{(\alpha/2)}$ = `r ifelse(xconf==90, 1.64, ifelse(xconf==95, 1.96, 2.58))`.
* "DE" es una aproximación a la desviación estándard 
* "d" se refiere a la *precisión* tambien llamado *desvío*

Aplicando la fórmula anterior:

$\scriptsize \begin{eqnarray}
\text{n} = \frac{(`r ifelse(xconf==90, 1.64, ifelse(xconf==95, 1.96, 2.58))`)^2 * \text{`r xsd`}^2}{\text{`r xprec`}^2} \thickapprox  `r nok[1]`
\end{eqnarray}$

*`r nok[1]` individuos son suficientes para estimar con un nivel de confianza del `r xconf`% y una precisión de $\pm$ `r xprec` mg/dl, la media de colesterol. Se asume que la DE es de aproximadamente `r xsd`*



Answerlist
----------
* Respuesta CORRECTA
* Respuesta Falsa
* Respuesta Falsa
* Respuesta Falsa
* Respuesta Falsa



Meta-information
================
exname: XXXXX
extype: schoice
exsolution: 10000
exshuffle: 5
